name: nuclei
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.4
  - pip=21.2.4
  - pytorch=1.11.0
  - scipy=1.7.3
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - pip:
    - imageio==2.19.3
    - matplotlib==3.5.2
    - numpy==1.22.4
    - oct2py==5.5.1
    - scikit-image==0.19.3
    - tqdm==4.64.0
    - loguru
